### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Adonai** [asmolko/MyDebts#5]
Apart from topic, we should track usage of Apache 2.0 and GPL licensed libraries used by us.

(E.g. License requirements include mention of author as a must.)

**Comment by Adonai** [comment]
And in fact, which license do we use? Classic GPLv3 or maybe some variations of beerware or WTFPL?

**Comment by demoth** [comment]
what are the play market restrictions?

**Comment by Adonai** [comment]
No restrictions on GPL'ed software, in contrast to AppStore.

**Comment by Adonai** [comment]
We don't have any more concerns about licensing issues as hackaton wasn't related to this code.
Let's add GPLv3 for now, we can always change it later if all collaborators agree.
